// Auto-generated by build.rs from src/constants.rs - DO NOT EDIT
// Edit src/constants.rs instead, then rebuild.

const WIDTH: f32 = 4434.0;
const HEIGHT: f32 = 2160.0;
const HEX_SIZE: f32 = 2640.0;
const HEX_FACTOR: f32 = 0.8660254;

const FLOW_FACTOR: f32 = 0.9;
const MAX_FLOW: f32 = 2640.0;

const KC: f32 = 3.0;
const KE: f32 = 0.14285715;
const KD: f32 = 0.00069444446;
const MAX_SLOPE: f32 = 1.0;
const MAX_ELEVATION: f32 = 16900.0;

const EVAPORATION_FACTOR: f32 = 0.0000003802652;
const BASIN_X_BOUNDARY: f32 = 4204.0;
const BASIN_Y_BOUNDARY: f32 = 897.0;
const NE_BASIN_MIN_ELEVATION: f32 = 600.0;

const ABYSSAL_PLAINS_MAX_DEPTH: f32 = -17100.0;
const CONTINENTAL_SHELF_DEPTH: f32 = 1000.0;
