// Auto-generated by build.rs from src/constants.rs - DO NOT EDIT
// Edit src/constants.rs instead, then rebuild.

const WIDTH: f32 = 4434.0;
const HEIGHT: f32 = 2160.0;
const HEX_SIZE: f32 = 2640.0;
const HEX_FACTOR: f32 = 0.8660254;

const FLOW_FACTOR: f32 = 0.9;
const MAX_FLOW: f32 = 2640.0;

const KC: f32 = 0.016;
const KE: f32 = 0.14285715;
const KD: f32 = 0.001;
const MAX_SLOPE: f32 = 1.0;
const MAX_ELEVATION: f32 = 16900.0;

const YEARS_PER_STEP: f32 = 0.0003911299;
const MAX_EVAPORATION_PER_YEAR: f32 = 2.0;
const BASIN_X_BOUNDARY: f32 = 4204.0;
const BASIN_Y_BOUNDARY: f32 = 897.0;
const NE_BASIN_MIN_ELEVATION: f32 = 800.0;

const ABYSSAL_PLAINS_MAX_DEPTH: f32 = -16800.0;
